新增主线推进模式
hgjazhgj/FGO-py pull request #118
Opened 2023-09-12 12:28 UTC by erictan2001

# 已完成gui及cli界面下运行主线推进模式，不過目前该模式只能在tw及na服下运行。
## 功能描述：
于显示next的界面即可使用，该模式自动帮你跳过剧情，选助战（选助战界面连续刷新3次后还没找到符合目标就选第一个），战斗，关闭通关特异点后出现的界面等等。目前在两服上测试稳定，身为萌新的我使用体验良好。
## 变更：
- fgoImage根目录下添加next.png，traitlist.png，skip.png。
- fgoKernel.py下添加BattleStory及MainStory类。
- fgoDetect.py下优化isSkillNone及isSkillReady。
- fgoDetect.py下更动getStage及getStageTotal：增添retry_count来解决侦测不了一直retry的情况。
- gui界面增添storymode选项，cli界面增加story指令。

## 未完成：
- 除了fgoImage/{tw,na}目录下其他服还缺startbutton,startquest和closebutton，其他服的截圖需要有玩的玩家提供。

2023-09-12 23:06 UTC, hgjazhgj requested changes
这是初步的review意见
由于更改较多,我会在你完成当前review中的内容后开始下一次review
请在你基本完成后ping我
特请注意,我对此review的质量较为不满
你需要更进一步地了解支撑FGO-py运行的基础机制,不要写想当然的代码
你也需要阅读现有的代码来维持一贯的风格

2023-09-12 23:13 UTC, hgjazhgj commented on FGO-py/fgoImage/friend/friend.png
如果这个文件是friend,那么上一个是什么
这个应该是「follow」,上一个是「friend」

2023-09-13 00:12 UTC, erictan2001 commented on FGO-py/fgoKernel.py
> +                elif self.click.clickClose():
有些剧情活动下选择战友后会给出提示需要关闭。

2023-09-13 00:16 UTC, erictan2001 commented on FGO-py/fgoImage/friend/freindicon.png
尴尬了打错字，这个是自己测试用的，待会重新提交时删掉。

2023-09-13 00:19 UTC, erictan2001 commented on FGO-py/fgoImage/dialogbox.png
好的,不过我想确认一下我用gimp处理图片时compression_level已经9了，想问这样的话还要再压缩吗？

2023-09-13 00:22 UTC, erictan2001 commented on FGO-py/fgoDetect.py
> +    def getCloseLoc(self):return (self._loc(self.tmpl.CLOSEBUTTON)[2],self.tmpl.CLOSEBUTTON[1].shape) if self._compare(self.tmpl.CLOSEBUTTON) else False
之前没注意到有个_find方法，我现在去改。

2023-09-13 00:24 UTC, erictan2001 commented on FGO-py/fgoImage/friend/friend.png
不好意思,一样是我个人测试时随便放的档案名，给你添麻烦了

2023-09-13 07:18 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +                elif self.click.clickClose():
> 有些剧情活动下选择战友后会给出提示需要关闭。

我希望能看到至少一张示例图片  
如果确实需要此判断,将其放置在MainStory.__call__中,不重写chooseFriend

2023-09-13 07:24 UTC, hgjazhgj commented on FGO-py/fgoImage/dialogbox.png
> 好的,不过我想确认一下我用gimp处理图片时compression_level已经9了，想问这样的话还要再压缩吗？

请照我说的做  
你提交的图片里有大量非图片数据,这是绝对不允许的  
![image](https://github.com/hgjazhgj/FGO-py/assets/40085173/63cbd82e-17a3-46a6-a91c-644af8e7ece8)  
请照我说的做,或者关闭此pr

2023-09-13 11:52 UTC, erictan2001 commented on FGO-py/fgoImage/dialogbox.png
我一直都不知道gimp竟然会加广告，这些图片我一定会改。第一次交pr真的挖了一堆坑，感觉大佬自己写的话都没指点我麻烦。真的感谢你花时间review我的pr。

2023-09-16 10:07 UTC, erictan2001 commented on FGO-py/fgoMainWindow.ui
> +        </item>
已调整成下列样式，不妥的话我再改。
![new_interface](https://github.com/hgjazhgj/FGO-py/assets/65934263/8e9cc602-a362-414b-8b87-1ba08d25302a)

2023-09-16 10:11 UTC, erictan2001 commented on FGO-py/fgoKernel.py
> +                elif self.click.clickClose():
剧情关卡限制时需关闭，已搬入MainStory.__call__内。
![Screenshot_2023-09-14_11 29 07 935](https://github.com/hgjazhgj/FGO-py/assets/65934263/8029d1f2-56e5-4488-b75b-d77f444d8490)

2023-09-27 16:51 UTC, erictan2001 commented
之前第一提交pr时各种考虑不周还请见谅，目前代码已根据项目风格进行调整与优化。
功能方面相较于未更改前而外兼容了活动的剧情推进。

目前测试了两个礼拜左右，个人在主线第一，二部，亚异闻带及活动上测试均无重大问题。
目前不能解决的是组队，通关特定关卡或集齐特定活动道具才能继续推动剧情等剧情限制，但这些太客制化的情况需玩家手动解决，短期内不考虑处理。

图形界面的更动如下：
![image](https://github.com/hgjazhgj/FGO-py/assets/65934263/e22f16a2-c0be-4e41-889d-847d1868a0d3)
此次pr的所有图片已用cv2.imwrite(filename,image,[cv2.IMWRITE_PNG_COMPRESSION,9])处理。额外添加的通用图片有dialogbox,next,skip和terminal，各服图片有closebutton,startbutton和startquest。各服图片目前只有tw及na目录下的完整，其他服的图片仍待补充。

这里稍微说明一下该pr额外添加的剧情推进模式：通过侦测并点击next来达到自动推进剧情的效果，模式运行期间会跳过剧情（如果无法跳过选择项就侦测选择项并点击），自动战斗和关闭期间所有提示。其他方面如选择队伍，吃苹果数，n场战斗后结束的判定皆无更改且可用。

然而next侦测方面我不太确定处理得是否妥当，剧情推进可能会出现不同且不固定比例的next，我的处理方法是按管制室图标退出该界面再进入，这时的next图像大小就会是固定的，但退回去的话无法保证进入的会是退出前的剧情界面（比如亚异闻带的剧情退回去的话均有next），如果有更好的办法或大佬觉得这样做不妥的话到时我再更改。

2023-09-28 01:33 UTC, hgjazhgj requested changes
这是进一步的修改意见
请注意你需要在**全部**完成之后再request review
部分出现多次的问题只写出了一处,你需要对每一个修改意见检查你的所有更改
你需要写出认真负责的代码

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/na/startbutton.png
图片中不得含有半透明像素
if the image you add has an Alpha channel, then this channel can only have two values: fully transparent (0) and fully opaque (255), and the transparent pixel itself must be pure black
你需要理解模板匹配整数蒙版的工作方式

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/skip.png
图片四周不得存在整行或整列的透明像素

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/tw/closebutton.png
为何文字内部有透明像素??

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +                        fgoDevice.device.touch((p[0],p[1]+75))if(p:=Detect.cache.getNextLoc())else fgoDevice.device.perform('\x1B',(300,))if Detect.cache.isStoryInterface()and time.time()-s>60 else f
非只读操作写成多行if-elif,不写三元运算
不得以字符串字面量作标志,同时,如果出现了标志变量,请尽量将其消除

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/na/closebutton.png
图片文件不得命名为*button

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/dialogbox.png
将此文件重命名为`dialogbar`

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoImage/terminal.png
只留左半边
![image](https://github.com/hgjazhgj/FGO-py/assets/40085173/57c3a17d-fc45-4eec-a96a-c6b88bd4be59)

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +            schedule.checkStopLater()
文件需要以LF结尾

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +       <string>在界面有next的情况下运行来推进剧情</string>
修改此处描述

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoTeamup.ini
不接受对teamup文件的更改

2023-09-28 01:33 UTC, hgjazhgj commented on deploy/AidLux/fgo_run_mode.sh
移除此shell

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +class MainStory(Main):
将此类重命名为Story

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoDetect.py
> +    def isStoryInterface(self):return self._compare(self.tmpl.TERMINAL,(0,0,185,90))
将此方法更名为`isStoryMap`,意为在地图界面

2023-09-28 01:33 UTC, hgjazhgj commented on FGO-py/fgoDetect.py
> +    def getNextStepLoc(self): return p if(p:=self._find(self.tmpl.ADDFRIEND,(940,590,1280,720)))else False
移除此方法

2023-09-28 01:43 UTC, hgjazhgj commented
> 之前第一提交pr时各种考虑不周还请见谅，目前代码已根据项目风格进行调整与优化。 功能方面相较于未更改前而外兼容了活动的剧情推进。
> 
> 目前测试了两个礼拜左右，个人在主线第一，二部，亚异闻带及活动上测试均无重大问题。 目前不能解决的是组队，通关特定关卡或集齐特定活动道具才能继续推动剧情等剧情限制，但这些太客制化的情况需玩家手动解决，短期内不考虑处理。
> 
> 图形界面的更动如下： ![image](https://user-images.githubusercontent.com/65934263/271050618-e22f16a2-c0be-4e41-889d-847d1868a0d3.png) 此次pr的所有图片已用cv2.imwrite(filename,image,[cv2.IMWRITE_PNG_COMPRESSION,9])处理。额外添加的通用图片有dialogbox,next,skip和terminal，各服图片有closebutton,startbutton和startquest。各服图片目前只有tw及na目录下的完整，其他服的图片仍待补充。
> 
> 这里稍微说明一下该pr额外添加的剧情推进模式：通过侦测并点击next来达到自动推进剧情的效果，模式运行期间会跳过剧情（如果无法跳过选择项就侦测选择项并点击），自动战斗和关闭期间所有提示。其他方面如选择队伍，吃苹果数，n场战斗后结束的判定皆无更改且可用。
> 
> 然而next侦测方面我不太确定处理得是否妥当，剧情推进可能会出现不同且不固定比例的next，我的处理方法是按管制室图标退出该界面再进入，这时的next图像大小就会是固定的，但退回去的话无法保证进入的会是退出前的剧情界面（比如亚异闻带的剧情退回去的话均有next），如果有更好的办法或大佬觉得这样做不妥的话到时我再更改。

目前请先把代码本身写好,我会在你完成当前请求的更改后再review

2023-10-04 02:34 UTC, hgjazhgj requested changes
你并未完成我之前提出的修改意见
请先将其完成,并再一次自查你所作出的更改

2023-10-04 02:34 UTC, hgjazhgj commented on FGO-py/fgoDetect.py
> +    def getSkillTargetCount(self):return(lambda x:numpy.bincount(numpy.diff(x))[1]+x[0])(cv2.dilate(numpy.max(cv2.threshold(numpy.max(self._crop((306,320,973,547)),axis=2),57,1,cv2.THRESH_BINARY)[1],
撤回此处更改  
你需要正确处理merge conflict

2023-10-04 02:34 UTC, hgjazhgj commented on FGO-py/fgoImage/terminal.png
图片四周不得存在整行或整列的透明像素

2023-10-04 02:34 UTC, hgjazhgj commented on FGO-py/fgoImage/dialogbar.png
The transparent pixel itself must be pure black  
另外这张图没扣干净

2023-10-04 02:34 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +       <string>在剧情界面有next的情况下运行</string>
修改此描述

2023-10-04 02:34 UTC, hgjazhgj commented on FGO-py/fgoDetect.py
> +    def findStartQuest(self):return self._find(self.tmpl.STARTQUEST,(695,520,985,605))
> 不允许在整个屏幕范围内find,需要指定区域  

我想,这些对象可能出现的区域坐标不会都能被5整除罢  
区域坐标需要**正好**比可能出现的区域大2px

> 如果一个对象总是在固定位置出现,就不得使用find  

如果一个对象可能出现的各个位置有相当的(足以点击的)部分重叠,也不得使用find  

此外,请重新审视这些方法名称

2023-10-05 08:52 UTC, erictan2001 commented on FGO-py/fgoDetect.py
> +    def findStartQuest(self):return self._find(self.tmpl.STARTQUEST,(695,520,985,605))
> 如果一个对象可能出现的各个位置有相当的(足以点击的)部分重叠,也不得使用find

这个说明指的是同时侦测到多个相同的对象然后这些对象重叠的情况吗?不然的话字面意义上理解的话那么"可能会出现在特定范围内各个位置的对象(比如next)"该怎么侦测?

2023-10-05 13:04 UTC, erictan2001 commented
> 如果一个对象可能出现的各个位置有相当的(足以点击的)部分重叠,也不得使用find

关于这点我不是很理解,不过已把只出现在固定位置的对象换成is系列函数,目前find系列函数只用来寻找close及next

## 自查
- 各服文件夹下的图片已统一命名成storystart, storyquest 和 storyclose并确保相同命名的图片大小相同, 所有图片均通过cv2.IMWRITE_PNG_COMPRESSION处理
- 因不确定statusTip可以如何更改得更妥当,翻译方面我把statusTip改成按键名
- fgoDetect下的函数已把范围确切限制在侦测对象出现范围各方向加2px
- 各语言翻译已通过pyside6-lrelease编译并运行程序检查确认均无问题
- merge conflict问题已处理, 申请review前也通过compare branch确认无错误merge

2023-10-05 15:09 UTC, hgjazhgj requested changes
此pr已经初具雏形，本次review只是初步的意见
我会在之后有空时仔细review，你可以不必急于作出改动

2023-10-05 15:09 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +                    if Detect.cache.isChooseFriend():self.chooseFriend()
此处是while not Detect(.3,.3).isBattleBegin()块结束后的语句
逻辑须修正，避免在isBattleBegin的界面上调用isChooseFriend和/或isTurnBegin

2023-10-05 15:14 UTC, hgjazhgj commented
> 如果一个对象可能出现的各个位置有相当的(足以点击的)部分重叠,也不得使用find

在这种情况下，应当点击重叠的位置而不需要根据对象所在的位置决定点击的位置

2023-10-05 16:28 UTC, erictan2001 commented on FGO-py/fgoKernel.py
> +            schedule.checkStopLater()
我没理解错的话LF结尾指的是end of line sequence格式选择LF吧?可是我这里看到的格式已经是LF了

2023-10-06 15:52 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +            schedule.checkStopLater()
> 我没理解错的话LF结尾指的是end of line sequence格式选择LF吧?可是我这里看到的格式已经是LF了

错误的
手动编写的文本文件的最后一个字节必须是LF,并且倒数第二个字节不能是空白和LF

2023-10-14 09:56 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +       <string>连续通关带有next标记的剧情关卡</string>
将此文本改为「在地图界面连续通关带有NEXT标记的关卡」

2023-10-14 10:00 UTC, hgjazhgj commented on FGO-py/fgoWebUI/index.html
> +    <button onclick="story()">剧情推进模式</button>
将此文本改为「剧情推进」

2023-10-14 10:05 UTC, hgjazhgj commented on FGO-py/fgoI18n.ja.ts
> +        <translation>BTN_STORY.text</translation>
ストーリーを進める

2023-10-14 10:09 UTC, hgjazhgj commented on FGO-py/fgoGui.py
> +    def explorerHere(self):os.startfile('.')if platform.system()=="Windows"else os.system("xdg-open .")if platform.system()=="Linux"else os.system("open .")
此处不写elseif连缀，改称
```python3
{
  'Windows':lambda:startfile('.'),
  ...
}.get(platform.system())()
```

2023-10-21 07:57 UTC, erictan2001 commented
进度自查
- 逻辑部分已修正,战斗前流程更改为isChooseFriend->isBattleBegin->之后的流程完全参照Main并在其基础添加判断
- 因剧情模式流程非固定,故流程上设定若遇到下一环节的判断对象就break(如在选择助战界面迴圈遇到战斗开始按钮就进入到战斗开始的判断迴圈)
- 然后LF结尾方面我已确认并无问题,无论是运行git ls-files --eol查看或是自行cat -A 文件均为LF结尾,如果有其他方法验证还请告知
![eol_fgo-py](https://github.com/hgjazhgj/FGO-py/assets/65934263/d087c5bb-089f-40b5-83b5-1626b129077c)

- html,ts及ui相关文件已按照comment修改

2023-10-21 10:48 UTC, hgjazhgj commented
![image](https://github.com/hgjazhgj/FGO-py/assets/40085173/77e9dadf-50be-4a9d-b16a-fc01f1ab8403)
这么显眼一个图标您是看不见吗

2023-10-21 11:05 UTC, hgjazhgj requested changes

2023-10-21 11:05 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +  <slot>runStory()</slot>
按字典序排列

2023-10-21 11:05 UTC, hgjazhgj commented on FGO-py/fgoKernel.py
> +                        if p:=Detect.cache.findStoryNext():
复读

2023-10-21 11:58 UTC, erictan2001 commented
> ![image](https://user-images.githubusercontent.com/40085173/277103803-77e9dadf-50be-4a9d-b16a-fc01f1ab8403.png) 这么显眼一个图标您是看不见吗

抱歉对github跟lf不熟悉结果一直都不知道那个图标是提醒lf错误的意思, 已更, 还望大佬见谅

2023-10-23 20:41 UTC, hgjazhgj commented on FGO-py/fgoGui.py
> +        {
将此左大括号移至上行行末

2023-10-23 20:53 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +     </connection>
撤回这些更改

2023-10-23 20:53 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +        <property name="statusTip">
为此按钮附加PointingHandCursor

2023-10-23 20:57 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +     <layout class="QHBoxLayout" name="LAYOUT_BATTLE">
此layout名保持LAYOUT_FUNC
而原本的LAYOUT_FUNC改名为LAYOUT_CONTROL
LAYOUT_FUNC_MAIN改名为LAYOUT_CONTROL_LEFT
LAYOUT_FUNC_CONTROL改名为LAYOUT_CONTROL_RIGHT

2023-10-23 20:59 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +       <widget class="QPushButton" name="BTN_STORY">
修正taborder

2023-10-23 21:04 UTC, hgjazhgj commented on FGO-py/fgoMainWindow.ui
> +       <widget class="QPushButton" name="BTN_CLASSIC">
修正为我描述的顺序

2024-11-04 12:21 UTC, closed without merging

2024-11-04 12:24 UTC, erictan2001 commented
搁置太久加上大佬已实现该类似功能，所以关闭此pr。