增加脚本管理员权限，修改 readme 中 windows 相关文档
hgjazhgj/FGO-py pull request #65
Opened 2022-08-14 15:47 UTC by geniusjoe

1. 增加脚本管理员权限，在运行脚本前会先弹出请求管理员权限，防止 windows 模拟器运行失败
2. 修改 readme 中 windows 相关文档，增加模拟器相关图片描述

2022-08-14 16:32 UTC, hgjazhgj requested changes
这会导致无论是否使用WindowsApi的相关功能FGO-py都会在启动时请求管理员权限,这是流氓行为,请仅在必要的时候申请管理员权限  
请问你在使用何种模拟器,满足:1.需要管理员权限;2.可以通过WindowsApi连接?

2022-08-14 16:38 UTC, geniusjoe commented
> 这会导致无论是否使用WindowsApi的相关功能FGO-py都会在启动时请求管理员权限,这是流氓行为,请仅在必要的时候申请管理员权限 请问你在使用何种模拟器,满足:1.需要管理员权限;2.可以通过WindowsApi连接?

@hgjazhgj 
[网易 mumu 模拟器](https://mumu.163.com/) 测试是需要管理员权限的，否则按 `i` 会直接退出

2022-08-14 16:40 UTC, geniusjoe commented
如果你用 adb 等方式没有遇到权限问题的话，我可以把请求权限的代码放在 fgoWindows.py 里

2022-08-14 16:45 UTC, hgjazhgj requested changes
请问你在使用何种模拟器,满足:1.需要管理员权限;2.可以通过WindowsApi连接?

2022-08-14 16:45 UTC, hgjazhgj commented on FGO-py/fgo.py
> +    admin.runAsAdmin()
这会导致无论是否使用WindowsApi的相关功能FGO-py都会在启动时请求管理员权限,这是流氓行为,请仅在必要的时候申请管理员权限

2022-08-14 16:45 UTC, hgjazhgj commented on FGO-py/admin.py
> +# https://gist.github.com/sylvainpelissier/ff072a6759082590a4fe8f7e070a4952
这个文件与本项目现有的代码风格不符,e.g.使用platform.system而非os.name进行系统判断
这是别人的代码,如果符合其开源许可,请移除包括注释在内的所有不必要部分,仅保留这行出处,并在本项目的LICENSE中追加相关许可(如有)

2022-08-14 16:47 UTC, hgjazhgj commented
> > 这会导致无论是否使用WindowsApi的相关功能FGO-py都会在启动时请求管理员权限,这是流氓行为,请仅在必要的时候申请管理员权限 请问你在使用何种模拟器,满足:1.需要管理员权限;2.可以通过WindowsApi连接?
> 
> @hgjazhgj [网易 mumu 模拟器](https://mumu.163.com/) 测试是需要管理员权限的，否则按 `i` 会直接退出

说实话我并不是很想为狗都不用排名第二的mumu模拟器添加支持  

是否有方法可以知晓目标窗口对应的进程是否具有管理员权限?
如果目标窗口有管理员权限而FGO-py没有,再申请

2022-08-14 17:09 UTC, hgjazhgj requested changes
这些图片不符合规范,请:
1.将其尺寸缩小至50%或更小
2.移除透明度通道
3.保存时指定[cv2.IMWRITE_PNG_COMPRESSION,9]来尽可能压缩png文件大小

2022-08-14 17:14 UTC, hgjazhgj requested changes
关于文档的相关修改意见

2022-08-14 17:14 UTC, hgjazhgj commented on readme.md
> +3. 如果能够成功响应，就在脚本中再次输入弹出窗口标题中的句柄即可。例子中句柄值为 `0xe16da`。
如果能够成功响应，应该直接在弹出的chuangkou中按`y`

2022-08-14 17:14 UTC, hgjazhgj commented on readme.md
> +2. 按下回车后，脚本会枚举鼠标指针正下方的可见窗口及其所有子窗口。在弹出窗口中确认展示的截图是 fgo 画面，按照弹出窗口标题中的说明，按 `i` 判断模拟器是否可以成功响应鼠标事件。
不要出现「脚本」字样
以「程序」「项目」「FGO-py」等替代,下同

2022-08-14 17:14 UTC, hgjazhgj commented on readme.md
> +### Windows 窗口 (安卓模拟器)
不要这个(安卓模拟器)
目标窗口不一定是安卓模拟器

2022-08-14 18:35 UTC, hgjazhgj commented on readme.md
> +2. 按下回车后,FGO-py会枚举鼠标指针正下方的可见窗口及其所有子窗口.确认弹出窗口中展示的截图是fgo画面后,按照弹出窗口标题中的说明,按 `i` 判断目标窗口是否可以成功响应鼠标事件
使用「」作为引号
「按 `i` 判断目标」这里还是有空格

2022-08-14 18:39 UTC, hgjazhgj commented on readme.md
> +4. 如果不能成功相应,则检查目标窗口是否使用管理员权限运行.如果是,则FGO-py也需要以管理员身份运行,设置如下所示
如果不能成功**响**应,则检查目标窗口是否**具有管理员权限**

2022-08-14 18:43 UTC, hgjazhgj commented on readme.md
> +
移除此处空行

2022-08-14 18:48 UTC, hgjazhgj requested changes
图片仍然不符合规范,请:
1.移除透明度通道
2.保存时指定[cv2.IMWRITE_PNG_COMPRESSION,9]来尽可能压缩png文件大小
3.移除文件名中编号的前导0

2022-08-14 19:03 UTC, merged

2022-08-14 19:13 UTC, geniusjoe commented on readme.md
> +4. 如果不能成功相应,则检查目标窗口是否使用管理员权限运行.如果是,则FGO-py也需要以管理员身份运行,设置如下所示
这个我还没改呢，老哥是你改还是我再提一个单子？

2022-08-15 03:04 UTC, geniusjoe commented
> > > 这会导致无论是否使用WindowsApi的相关功能FGO-py都会在启动时请求管理员权限,这是流氓行为,请仅在必要的时候申请管理员权限 请问你在使用何种模拟器,满足:1.需要管理员权限;2.可以通过WindowsApi连接?
> > 
> > 
> > @hgjazhgj [网易 mumu 模拟器](https://mumu.163.com/) 测试是需要管理员权限的，否则按 `i` 会直接退出
> 
> 说实话我并不是很想为狗都不用排名第二的mumu模拟器添加支持
> 
> 是否有方法可以知晓目标窗口对应的进程是否具有管理员权限? 如果目标窗口有管理员权限而FGO-py没有,再申请


ok，我看你改了 readme 了 🤣
查询某个进程是否具有管理员权限我查了下 [相关提问](https://stackoverflow.com/questions/59801177/use-python-to-check-if-some-process-is-running-as-administrator)，貌似没有直接的 api 可以调用，感觉就算了，直接让用户手动授权好了
>
> Neither the standard library nor psutil contains a function to check whether the user of another process is an administrator. You'll need to use ctypes or PyWin32 to access the Windows API directly.
>

2022-08-15 07:14 UTC, hgjazhgj commented
本项目本就有些许功能是 use ctypes to access the Windows API directly实现的
所以有这样的API吗?
我的担心是这样的API本就需要管理员权限...